# Generated by Django 5.2.3 on 2025-07-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_by',
            new_name='created_at',
        ),
    ]
